#' @title DATASET_TITLE
#' @description DATASET_DESCRIPTION
#' @format A data frame with 2219 rows and 86 variables:
#' \describe{
#'   \item{\code{CVE_MUN}}{character COLUMN_DESCRIPTION}
#'   \item{\code{CVE_LOC}}{character COLUMN_DESCRIPTION}
#'   \item{\code{acc_1health}}{double COLUMN_DESCRIPTION}
#'   \item{\code{acc_2health}}{double COLUMN_DESCRIPTION}
#'   \item{\code{acc_3health}}{double COLUMN_DESCRIPTION}
#'   \item{\code{acc_presc}}{double COLUMN_DESCRIPTION}
#'   \item{\code{acc_elem}}{double COLUMN_DESCRIPTION}
#'   \item{\code{acc_sec}}{double COLUMN_DESCRIPTION}
#'   \item{\code{acc_dev}}{double COLUMN_DESCRIPTION}
#'   \item{\code{PHOGJEF_F}}{double COLUMN_DESCRIPTION}
#'   \item{\code{PPCON_DISC}}{double COLUMN_DESCRIPTION}
#'   \item{\code{PROM_HNV}}{double COLUMN_DESCRIPTION}
#'   \item{\code{GRAPROES_F}}{double COLUMN_DESCRIPTION}
#'   \item{\code{PP_60YMAS}}{double COLUMN_DESCRIPTION}
#'   \item{\code{PP_15YMAS}}{double COLUMN_DESCRIPTION}
#'   \item{\code{PP12YM_SEPA}}{double COLUMN_DESCRIPTION}
#'   \item{\code{PP6A11_NOA}}{double COLUMN_DESCRIPTION}
#'   \item{\code{CPRESOE15}}{double COLUMN_DESCRIPTION}
#'   \item{\code{CP12YM_SOLT}}{double COLUMN_DESCRIPTION}
#'   \item{\code{CHOGJEF_F}}{double COLUMN_DESCRIPTION}
#'   \item{\code{CPSIN_RELIG}}{double COLUMN_DESCRIPTION}
#'   \item{\code{CP12YM_SEPA}}{double COLUMN_DESCRIPTION}
#'   \item{\code{CGRAPROES}}{double COLUMN_DESCRIPTION}
#'   \item{\code{PPEA}}{double COLUMN_DESCRIPTION}
#'   \item{\code{PPOCUPADA}}{double COLUMN_DESCRIPTION}
#'   \item{\code{GRAPROES}}{double COLUMN_DESCRIPTION}
#'   \item{\code{PPDER_SS}}{double COLUMN_DESCRIPTION}
#'   \item{\code{PP18A24A}}{double COLUMN_DESCRIPTION}
#'   \item{\code{CPEA}}{double COLUMN_DESCRIPTION}
#'   \item{\code{PVIVTOT}}{double COLUMN_DESCRIPTION}
#'   \item{\code{PTOTHOG}}{double COLUMN_DESCRIPTION}
#'   \item{\code{POCUPVIVPAR}}{double COLUMN_DESCRIPTION}
#'   \item{\code{PROM_OCUP}}{double COLUMN_DESCRIPTION}
#'   \item{\code{PRO_OCUP_C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{PVPH_INTER}}{double COLUMN_DESCRIPTION}
#'   \item{\code{PVPH_CEL}}{double COLUMN_DESCRIPTION}
#'   \item{\code{PVPH_TIC}}{double COLUMN_DESCRIPTION}
#'   \item{\code{PVPH_C_SERV}}{double COLUMN_DESCRIPTION}
#'   \item{\code{PVPH_AEASP}}{double COLUMN_DESCRIPTION}
#'   \item{\code{edu_pcapita}}{double COLUMN_DESCRIPTION}
#'   \item{\code{tot_pcapita}}{double COLUMN_DESCRIPTION}
#'   \item{\code{tot_denue}}{double COLUMN_DESCRIPTION}
#'   \item{\code{tot_emp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{prop_emp}}{double COLUMN_DESCRIPTION}
#'   \item{\code{no_bpesca}}{double COLUMN_DESCRIPTION}
#'   \item{\code{bpesca_perc}}{double COLUMN_DESCRIPTION}
#'   \item{\code{no_seed}}{double COLUMN_DESCRIPTION}
#'   \item{\code{seed_perc}}{double COLUMN_DESCRIPTION}
#'   \item{\code{no_bengas}}{double COLUMN_DESCRIPTION}
#'   \item{\code{bengas_perc}}{double COLUMN_DESCRIPTION}
#'   \item{\code{no_boat}}{double COLUMN_DESCRIPTION}
#'   \item{\code{boat_perc}}{double COLUMN_DESCRIPTION}
#'   \item{\code{no_comm}}{double COLUMN_DESCRIPTION}
#'   \item{\code{comm_perc}}{double COLUMN_DESCRIPTION}
#'   \item{\code{no_aqua}}{double COLUMN_DESCRIPTION}
#'   \item{\code{aqua_perc}}{double COLUMN_DESCRIPTION}
#'   \item{\code{no_cons}}{double COLUMN_DESCRIPTION}
#'   \item{\code{cons_perc}}{double COLUMN_DESCRIPTION}
#'   \item{\code{no_value}}{double COLUMN_DESCRIPTION}
#'   \item{\code{value_perc}}{double COLUMN_DESCRIPTION}
#'   \item{\code{no_str}}{double COLUMN_DESCRIPTION}
#'   \item{\code{str_perc}}{double COLUMN_DESCRIPTION}
#'   \item{\code{no_ins}}{double COLUMN_DESCRIPTION}
#'   \item{\code{ins_perc}}{double COLUMN_DESCRIPTION}
#'   \item{\code{no_leg}}{double COLUMN_DESCRIPTION}
#'   \item{\code{leg_perc}}{double COLUMN_DESCRIPTION}
#'   \item{\code{no_eff}}{double COLUMN_DESCRIPTION}
#'   \item{\code{eff_perc}}{double COLUMN_DESCRIPTION}
#'   \item{\code{no_gen}}{double COLUMN_DESCRIPTION}
#'   \item{\code{gen_perc}}{double COLUMN_DESCRIPTION}
#'   \item{\code{anp_area_loc_kmsq}}{double COLUMN_DESCRIPTION}
#'   \item{\code{social_indx}}{double COLUMN_DESCRIPTION}
#'   \item{\code{ANALF}}{double COLUMN_DESCRIPTION}
#'   \item{\code{SBASC}}{double COLUMN_DESCRIPTION}
#'   \item{\code{OVSDE}}{double COLUMN_DESCRIPTION}
#'   \item{\code{OVSEE}}{double COLUMN_DESCRIPTION}
#'   \item{\code{OVSAE}}{double COLUMN_DESCRIPTION}
#'   \item{\code{OVPT}}{double COLUMN_DESCRIPTION}
#'   \item{\code{OVHAC}}{double COLUMN_DESCRIPTION}
#'   \item{\code{OVSREF}}{double COLUMN_DESCRIPTION}
#'   \item{\code{IM_2020}}{double COLUMN_DESCRIPTION}
#'   \item{\code{tm_serv}}{double COLUMN_DESCRIPTION}
#'   \item{\code{deg_access}}{double COLUMN_DESCRIPTION}
#'   \item{\code{pav_dis}}{double COLUMN_DESCRIPTION}
#'   \item{\code{dis_pub}}{double COLUMN_DESCRIPTION}
#'   \item{\code{aqui_dis}}{double COLUMN_DESCRIPTION} 
#'}
#' @details DETAILS
"adaptivecapacitydata"